services:
  mysql:
    image: mysql:8.0.38
    container_name: mysql-lab
    ports:
      - "${MYSQL_PORT}:${MYSQL_CONTAINER_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      TZ: "${TZ}"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - lab-management-network
    restart: unless-stopped
    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --default-authentication-plugin=mysql_native_password
      --init-file=/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mail-dev:
    image: maildev/maildev
    container_name: mail-dev-lab
    ports:
      - "${MAILDEV_SMTP_PORT}:1025"
      - "${MAILDEV_WEB_PORT}:1080"


  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - lab-management-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false #turn off security for dev mode
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - lab-management-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.5
    container_name: logstash
    ports:
      - "${LOGSTASH_PORT}:5044"
      - "${LOGSTASH_MONITORING_PORT}:9600"
    environment:
      - XPACK_MONITORING_ENABLED=false
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    networks:
      - lab-management-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.5
    container_name: kibana
    ports:
      - "${KIBANA_PORT}:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      - lab-management-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.16.5
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - springboot-logs:/logs:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro  # Gắn file cấu hình
    networks:
      - lab-management-network  # Kết nối với mạng chung
    depends_on:
      - logstash
      - springboot-app
    user: root


  springboot-app:
    container_name: lab_management_be
    build:
      context: .
      args:
        - PROFILE=${SPRING_PROFILES_ACTIVE}
        - APP_VERSION=0.0.1-SNAPSHOT
    volumes:
      - springboot-logs:/logs
    ports:
      - "${SPRINGBOOT_PORT}:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_CONTAINER_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_URL=jdbc:mysql://mysql:${MYSQL_CONTAINER_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&useSSL=false
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - VITE_HOST=${VITE_HOST:-192.168.100.106}
      - VITE_PORT=${VITE_PORT:-5173}
    networks:
      - lab-management-network
    depends_on:
      - mysql
      - redis
      - logstash

  vite-typescript-app:
    container_name: lab_management_ui
    build:
      context: ../lab_management_ui
    ports:
      - "${VITE_PORT}:80"
    networks:
      - lab-management-network
    depends_on:
      - springboot-app


volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
  springboot-logs:

networks:
  lab-management-network:
    driver: bridge
