spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true            # Kích hoạt multipart
      max-file-size: 50MB       # Kích thước file tối đa cho phép
      max-request-size: 50MB    # Kích thước request tối đa

